version: "3"

services: 
  database-service:
    container_name: db-service
    image: iamchaitanyakulkarni/db-service
    restart: always
    build: 
      context: ./database-service
      dockerfile: Dockerfile
    ports: 
      - "3000:3000"
    links: 
      - mongo
    environment: 
        - MONGO_URL=mongodb://mongo:27017/StockPrediction

  stock-service:
    container_name: stock-service
    image: iamchaitanyakulkarni/stock-service
    restart: always
    build: 
      context: ./stock-service
      dockerfile: Dockerfile
    ports: 
      - "4000:4000"
    links: 
      - mongo
    environment: 
        - MONGO_URL=mongodb://mongo:27017/StockPrediction

  ui-service:
    container_name: ui-service
    image: iamchaitanyakulkarni/ui-service
    restart: always
    build: 
      context: ./ui-service
      dockerfile: Dockerfile
    ports: 
      - "5000:5000"
    links: 
      - mongo
    
  prediction-service:
    container_name: prediction-service
    image: iamchaitanyakulkarni/prediction-service
    restart: always
    build: 
      context: ./stock_prediction
      dockerfile: Dockerfile
    ports: 
      - "5050:5050"

  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27018:27017"